In [102]:
import pandas as pd

In [103]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')

In [104]:
df.head(2)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3

In [105]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [106]:
df.shape

(10000, 11)

In [107]:
df.fuel_type.nunique()

3

In [108]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [109]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [110]:
df[df.origin == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [111]:
df.horsepower.mean()

np.float64(254.44601556505535)

In [112]:
df.horsepower.unique()

array([243., 272., 267., 258., 304., 266., 250., 279., 251., 280.,  nan,
       277., 202., 226., 234., 299., 264., 260., 291., 246., 302., 249.,
       254., 265., 216., 294., 240., 255., 273., 270., 262., 296., 239.,
       248., 282., 238., 231., 289., 232., 321., 235., 257., 284., 233.,
       198., 221., 290., 219., 263., 256., 210., 252., 261., 268., 283.,
       237., 298., 278., 229., 241., 244., 245., 228., 269., 247., 236.,
       259., 200., 224., 275., 271., 285., 242., 295., 213., 253., 297.,
       220., 230., 287., 274., 214., 313., 288., 225., 305., 186., 212.,
       318., 218., 286., 276., 281., 211., 306., 222., 217., 227., 207.,
       308., 209., 181., 197., 205., 309., 206., 208., 201., 204., 223.,
       310., 215., 300., 293., 292., 195., 307., 203., 187., 317., 194.,
       301., 328., 312., 327., 329., 199., 324., 326., 191., 311., 334.,
       188., 190., 303., 319., 314., 325., 316., 182., 171., 332., 315.,
       196., 174., 193., 184., 322., 192., 330., 323., 175., 178., 320.])

In [113]:
df.horsepower.value_counts()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [114]:
df.horsepower.isnull().sum()

np.int64(877)

In [115]:
df.horsepower = df.horsepower.fillna(252)

In [116]:
df.horsepower.isnull().sum()

np.int64(0)

In [117]:
df.horsepower.mean()

np.float64(254.2315)

In [118]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [119]:
x = df[df.origin == 'Asia'][['vehicle_weight', 'model_year']].head(7).values
x

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [120]:
import numpy as np

In [121]:
t = x.T
t

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [122]:
xtx = t.dot(x)
xtx

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [123]:
np.linalg.inv(xtx)

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [124]:
y=[1100, 1300, 800, 900, 1000, 1100, 1200]
y = np.array(y)

In [125]:
w = np.linalg.inv(xtx).dot(t).dot(y)
w

array([0.13644777, 0.2327492 ])

In [127]:
w.sum()

np.float64(0.36919696904925486)